spring:
  profiles:
    active: dev

server:
  port: 1002
spring:
  profiles:
    active: dev
      applications:
        name: microservice_config_dev

server:
  port:1003
spring:
  profiles:
    active: prod
      applications:
        name: microservice_config_prod